const YEAR='2026';
const SITE='https://techguru.atechspot.com';
const SECURITY={
  'content-security-policy':"default-src 'self'; img-src 'self' data: https:; style-src 'self' 'unsafe-inline'; script-src 'none'; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self' https://support.atechspot.com https://remotecare.atechspot.com",
  'x-content-type-options':'nosniff',
  'x-frame-options':'DENY',
  'referrer-policy':'strict-origin-when-cross-origin',
  'permissions-policy':'camera=(), microphone=(), geolocation=(), payment=(), usb=()',
  'strict-transport-security':'max-age=31536000; includeSubDomains'
};
const css=`:root{--bg:#06111b;--panel:#0b1b29;--panel2:#0f2537;--line:#1b3a53;--text:#eef9ff;--muted:#9db1c2;--cyan:#65dff0;--green:#70e4b2;--warn:#ffd27a}*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:radial-gradient(circle at 82% 0,#113d58 0,transparent 34%),var(--bg);color:var(--text);font-family:Inter,Arial,sans-serif}a{color:inherit;text-decoration:none}.wrap{width:min(1160px,calc(100% - 32px));margin:auto}.top{padding:9px;text-align:center;background:#071827;color:#bfd3e1;font-size:10px;font-weight:900;letter-spacing:.14em}.nav{position:sticky;top:0;z-index:10;background:#06111be8;backdrop-filter:blur(14px);border-bottom:1px solid var(--line)}.nav .wrap{height:74px;display:flex;align-items:center;gap:22px}.brand{margin-right:auto;font-size:21px;font-weight:950}.brand b{color:var(--cyan)}.nav a:not(.brand){font-size:13px;color:#c4d6e2}.btn{display:inline-block;padding:13px 18px;border-radius:999px;background:var(--cyan);color:#041018!important;font-weight:900}.hero{padding:100px 0 78px}.eyebrow{font-size:11px;letter-spacing:.18em;font-weight:900;text-transform:uppercase;color:var(--green)}h1,h2{letter-spacing:-.05em;line-height:.97}h1{font-size:clamp(52px,8vw,92px);max-width:1000px;margin:16px 0 24px}h2{font-size:clamp(38px,5vw,64px);margin:12px 0 22px}.lead,.hero p{max-width:820px;color:var(--muted);font-size:18px;line-height:1.72}.actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:27px}.ghost{background:transparent!important;border:1px solid var(--line);color:var(--text)!important}.section{padding:78px 0;border-top:1px solid var(--line)}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.card{padding:25px;border:1px solid var(--line);border-radius:20px;background:linear-gradient(145deg,var(--panel2),var(--panel))}.card small{color:var(--cyan);font-weight:900;letter-spacing:.12em}.card h3{font-size:21px;margin:13px 0 9px}.card p,.card li{color:var(--muted);line-height:1.65}.card ul{padding-left:18px}.alert{padding:22px;border:1px solid #5b4d25;background:#231d0c;border-radius:18px;color:#f0d99f}.band{background:#081724}.steps{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.step{padding:22px;border:1px solid var(--line);border-radius:18px;background:#0a1b29}.step b{display:grid;place-items:center;width:36px;height:36px;border-radius:50%;background:var(--cyan);color:#041018}.step p{color:var(--muted);line-height:1.6}.footer{padding:46px 0;border-top:1px solid var(--line);color:#91a6b6;font-size:12px}.footer a{color:#dff7ff;margin-right:14px}@media(max-width:860px){.grid{grid-template-columns:1fr 1fr}.steps{grid-template-columns:1fr 1fr}.nav a:not(.brand):not(.btn){display:none}}@media(max-width:560px){.grid,.steps{grid-template-columns:1fr}.hero{padding-top:72px}.nav .btn{display:none}}`;
const head=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ATechSpot Tech Guru | DIY Technology Help</title><meta name="description" content="Practical DIY technology help from the ATechSpot ecosystem. Learn safe first steps, troubleshoot common issues, and escalate to RemoteCare when you need hands-on support."><link rel="canonical" href="${SITE}/"><meta name="robots" content="index,follow,max-image-preview:large"><meta property="og:title" content="ATechSpot Tech Guru"><meta property="og:description" content="DIY technology help with a clear path to professional support."><meta property="og:url" content="${SITE}/"><meta property="og:type" content="website"><meta name="theme-color" content="#06111b"><style>${css}</style></head><body>`;
const nav=`<div class="top">ATechSPOT ECOSYSTEM • DIY TECHNOLOGY HELP • PROPERTY 22 OF 22</div><nav class="nav"><div class="wrap"><a class="brand" href="/">ATechSpot <b>Tech Guru</b></a><a href="#guides">Guides</a><a href="#process">Troubleshoot</a><a href="#safety">Safety</a><a class="btn" href="https://remotecare.atechspot.com/">Get Remote Help →</a></div></nav>`;
const foot=`<footer class="footer"><div class="wrap"><strong>ATechSpot Tech Guru</strong><p>DIY technology education connected to ATechSpot RemoteCare and the wider A+ Techucation ecosystem.</p><p><a href="https://www.atechspot.com/ecosystem/">Ecosystem</a><a href="https://support.atechspot.com/">Support</a><a href="https://remotecare.atechspot.com/">RemoteCare</a><a href="https://www.atechspot.com/contact/">Contact</a></p><p>© ${YEAR} A+ Techucation LLC d/b/a ATechSpot.</p></div></footer>`;
const home=`${head}${nav}<main><section class="hero"><div class="wrap"><div class="eyebrow">Fix what you can. Escalate what you should.</div><h1>Technology help that starts with the simplest safe step.</h1><p>Tech Guru is the self-service technology-help layer of the ATechSpot ecosystem. Use it to understand common computer, connectivity, account, device and setup problems—then move into RemoteCare when the issue needs hands-on support.</p><div class="actions"><a class="btn" href="#guides">Start troubleshooting →</a><a class="btn ghost" href="https://remotecare.atechspot.com/">Request RemoteCare</a></div></div></section>
<section class="section" id="guides"><div class="wrap"><div class="eyebrow">Common starting points</div><h2>Start with the symptom.</h2><div class="grid">
<article class="card"><small>COMPUTER</small><h3>Slow, frozen or unstable</h3><p>Start with restart, storage, updates, startup apps and recent changes before assuming hardware failure.</p></article>
<article class="card"><small>INTERNET</small><h3>Wi-Fi or connectivity trouble</h3><p>Separate device problems from router, modem and provider problems with a simple isolation sequence.</p></article>
<article class="card"><small>ACCOUNTS</small><h3>Login or password problems</h3><p>Use official recovery methods, verify the domain, and avoid sharing one-time codes or passwords with anyone.</p></article>
<article class="card"><small>DEVICES</small><h3>Printer, phone or accessory setup</h3><p>Check power, connection method, permissions, drivers and software before replacing equipment.</p></article>
<article class="card"><small>FILES</small><h3>Missing or inaccessible data</h3><p>Stop unnecessary writes to a failing drive. Important data-loss cases may need professional recovery rather than repeated DIY attempts.</p></article>
<article class="card"><small>SECURITY</small><h3>Suspicious pop-ups or messages</h3><p>Do not install unknown remote-access tools, disclose credentials, or call phone numbers shown in scareware pop-ups.</p></article>
</div></div></section>
<section class="section band" id="process"><div class="wrap"><div class="eyebrow">Four-step troubleshooting method</div><h2>Observe before you change.</h2><div class="steps"><div class="step"><b>1</b><h3>Identify</h3><p>Write down the exact symptom, error, device and when the problem started.</p></div><div class="step"><b>2</b><h3>Isolate</h3><p>Determine whether the issue follows one device, one account, one network or one application.</p></div><div class="step"><b>3</b><h3>Try safely</h3><p>Use reversible steps first: restart, update, reconnect, verify settings and test another device.</p></div><div class="step"><b>4</b><h3>Escalate</h3><p>Stop when the next step risks data, security, warranty coverage or business continuity.</p></div></div></div></section>
<section class="section" id="safety"><div class="wrap"><div class="eyebrow">Safety boundary</div><h2>Some problems should not be DIY.</h2><div class="alert"><strong>Stop and get professional help</strong> if you suspect active fraud, malware with sensitive-data exposure, electrical damage, a physically failing storage device, a business-critical outage, or a repair step that could erase irreplaceable data.</div><div class="actions"><a class="btn" href="https://remotecare.atechspot.com/">Open RemoteCare →</a><a class="btn ghost" href="https://www.atechspot.com/data-recovery/">Data Recovery Options</a></div></div></section>
<section class="section"><div class="wrap"><div class="eyebrow">Connected support system</div><h2>DIY knowledge plus professional escalation.</h2><p class="lead">Tech Guru is educational. RemoteCare is the paid support path. ATechSpot handles larger business technology, website, AI, automation and software needs. Keeping these roles separate makes it clearer what you can solve yourself and when to bring in help.</p><div class="actions"><a class="btn" href="https://support.atechspot.com/">Support Center →</a><a class="btn ghost" href="https://www.atechspot.com/">ATechSpot</a></div></div></section></main>${foot}</body></html>`;
function out(body,status=200,type='text/html; charset=utf-8'){return new Response(body,{status,headers:{'content-type':type,'cache-control':status===200?'public, max-age=180':'no-store',...SECURITY}})}
export default{async fetch(request){const u=new URL(request.url),p=u.pathname.replace(/\/+$/,'')||'/';if(p==='/api/health')return out(JSON.stringify({ok:true,property:'ATechSpot Tech Guru',canonical:SITE}),200,'application/json; charset=utf-8');if(p==='/robots.txt')return out('User-agent: *\nAllow: /\nSitemap: '+SITE+'/sitemap.xml',200,'text/plain; charset=utf-8');if(p==='/sitemap.xml')return out('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>'+SITE+'/</loc></url></urlset>',200,'application/xml; charset=utf-8');if(p==='/')return out(home);return out(home.replace('</main>','<section class="section"><div class="wrap"><div class="eyebrow">404</div><h2>Page not found.</h2><p><a class="btn" href="/">Return to Tech Guru →</a></p></div></section></main>'),404)}};