const SITE='https://start.atechspot.com/';
const MAIN='https://www.atechspot.com';
const SECURITY={
  'x-content-type-options':'nosniff',
  'x-frame-options':'DENY',
  'referrer-policy':'strict-origin-when-cross-origin',
  'permissions-policy':'camera=(), microphone=(), geolocation=(), payment=(), usb=()',
  'strict-transport-security':'max-age=31536000',
  'content-security-policy':"default-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; script-src 'self'; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; object-src 'none'; upgrade-insecure-requests"
};
const css=`:root{--bg:#06111c;--panel:#0d1c2a;--line:#1b3650;--text:#eef8ff;--muted:#9eb3c4;--accent:#74d3ff;--green:#70e1b5}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 80% 0,#123a5b 0,transparent 34%),var(--bg);color:var(--text);font-family:Inter,Arial,sans-serif}.wrap{width:min(1120px,calc(100% - 32px));margin:auto}.top{padding:9px;text-align:center;background:#0a2135;font-size:10px;font-weight:900;letter-spacing:.13em}.nav{border-bottom:1px solid var(--line);background:#06111cee}.nav .wrap{height:72px;display:flex;align-items:center;gap:20px}.brand{margin-right:auto;font-size:21px;font-weight:900;color:var(--text);text-decoration:none}.brand b{color:var(--accent)}.nav a{color:#c8d8e5;text-decoration:none;font-size:13px}.hero{padding:96px 0 72px}.eyebrow{color:var(--green);font-size:11px;font-weight:900;letter-spacing:.17em;text-transform:uppercase}.hero h1{font-size:clamp(46px,7vw,82px);line-height:.96;letter-spacing:-.055em;margin:14px 0 22px}.hero p{max-width:820px;color:var(--muted);font-size:18px;line-height:1.75}.section{padding:74px 0;border-top:1px solid var(--line)}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.card{padding:25px;border:1px solid var(--line);border-radius:18px;background:linear-gradient(145deg,#10263a,#0a1723)}.card h2{font-size:21px;margin:0 0 9px}.card p{color:var(--muted);line-height:1.65}.card a{color:var(--accent);font-weight:850;text-decoration:none}.foot{padding:44px 0;border-top:1px solid var(--line);color:var(--muted);font-size:12px}.foot a{color:#d8ecfa;margin-right:14px}@media(max-width:800px){.grid{grid-template-columns:1fr 1fr}.nav a:not(.brand){display:none}}@media(max-width:560px){.grid{grid-template-columns:1fr}.hero{padding-top:70px}}`;
const page=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Start with ATechSpot | Choose Your Next Step</title><meta name="description" content="Choose the right ATechSpot path for assessment, project intake, consultation, technical support or active-client access."><meta name="robots" content="noindex,follow"><link rel="canonical" href="${SITE}"><meta name="theme-color" content="#06111c"><style>${css}</style></head><body><div class="top">A+ TECHUCATION • ATECHSPOT CUSTOMER START</div><nav class="nav"><div class="wrap"><a class="brand" href="${MAIN}/">A+ <b>ATechSpot</b></a><a href="${MAIN}/ecosystem/">Ecosystem</a><a href="https://support.atechspot.com/">Support</a><a href="${MAIN}/contact/">Contact</a></div></nav><main><section class="hero"><div class="wrap"><div class="eyebrow">Start Here</div><h1>Choose the right next step.</h1><p>Use the path that best matches what you need. You do not need to know which ATechSpot service or ecosystem property is right before you begin.</p></div></section><section class="section"><div class="wrap"><div class="grid"><article class="card"><h2>Free Growth Assessment</h2><p>Identify the highest-priority technology or growth opportunity.</p><a href="${MAIN}/assessment/">Take the assessment →</a></article><article class="card"><h2>Project Intake</h2><p>Tell us what you want to build, fix, launch or improve.</p><a href="https://intake.atechspot.com/">Start intake →</a></article><article class="card"><h2>Book a Conversation</h2><p>Choose an available consultation time after sharing enough context.</p><a href="https://book.atechspot.com/">View booking →</a></article><article class="card"><h2>Technical Support</h2><p>Get help with eligible device, software, setup or connectivity issues.</p><a href="https://support.atechspot.com/">Open support →</a></article><article class="card"><h2>Active Client Access</h2><p>Open the secure portal for an authorized active client account.</p><a href="https://clients.atechspot.com/">Client portal →</a></article><article class="card"><h2>Explore the Ecosystem</h2><p>Browse specialist brands, services and connected systems.</p><a href="${MAIN}/ecosystem/">Explore ecosystem →</a></article></div></div></section></main><footer class="foot"><div class="wrap"><strong>ATechSpot Start</strong><p><a href="${MAIN}/privacy/">Privacy</a><a href="${MAIN}/terms/">Terms</a><a href="https://help.atechspot.com/">Help</a></p><p>© 2026 A+ Techucation LLC / ATechSpot.</p></div></footer></body></html>`;
function out(body,status=200,type='text/html; charset=utf-8'){return new Response(body,{status,headers:{'content-type':type,'cache-control':'no-store',...SECURITY}})}
export default{async fetch(request){const u=new URL(request.url);if(u.pathname==='/api/health')return out(JSON.stringify({ok:true,property:'ATechSpot Start',canonical:SITE}),200,'application/json; charset=utf-8');if(u.pathname!=='/'&&u.pathname!=='')return Response.redirect(SITE,308);return out(page)}};
