
const HEADERS={"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"};
const BLOCKED=[/\b(?:viagra|cialis|casino|forex|guest post|backlinks?|seo package|crypto investment)\b/i,/<\s*(?:script|iframe|object|embed)\b/i,/\b(?:javascript:|onerror\s*=|onload\s*=)\b/i];
const reply=(status,message)=>new Response(JSON.stringify({ok:status<400,message}),{status,headers:HEADERS});
const clean=(v,max=2000)=>String(v??"").replace(/\u0000/g,"").trim().slice(0,max);
const validEmail=v=>/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/i.test(v)&&v.length<=254;
const spam=text=>BLOCKED.some(p=>p.test(text))||((text.match(/https?:\/\/|www\./gi)||[]).length>2);
const esc=v=>String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;"); async function verify(token,secret,ip,hostname){ if(!token||!secret)return{success:false}; const fd=new FormData(); fd.append("secret",secret);fd.append("response",token); if(ip)fd.append("remoteip",ip); fd.append("idempotency_key",crypto.randomUUID()); const r=await fetch("https://challenges.cloudflare.com/turnstile/v0/siteverify",{method:"POST",body:fd}); const result=await r.json(); if(result.success&&result.hostname!==hostname)return{success:false}; return result;
} async function email(env,subject,replyTo,fields,meta){ if(!env.RESEND_API_KEY||!env.FORM_TO_EMAIL||!env.FORM_FROM_EMAIL)throw new Error("Email not configured"); const rows=Object.entries(fields).map(([k,v])=>`<tr><th style="text-align:left;padding:8px;border:1px solid #ddd">${esc(k)}</th><td style="padding:8px;border:1px solid #ddd">${esc(v).replace(/\n/g,"<br>")}</td></tr>`).join(""); const r=await fetch("https://api.resend.com/emails",{method:"POST",headers:{"authorization":`Bearer ${env.RESEND_API_KEY}`,"content-type":"application/json"},body:JSON.stringify({ from:env.FORM_FROM_EMAIL,to:[env.FORM_TO_EMAIL],reply_to:replyTo,subject, html:`<div style="font-family:Arial,sans-serif;max-width:720px"><h2>${esc(subject)}</h2><table style="border-collapse:collapse;width:100%">${rows}</table><p style="font-size:12px;color:#667085">Host: ${esc(meta.host)}<br>Submitted: ${esc(meta.time)}</p></div>` })}); if(!r.ok)throw new Error(`Email ${r.status}`);
} export async function onRequestPost({request,env}){ if(!(request.headers.get("content-type")||"").includes("application/json"))return reply(415,"Unsupported submission."); if(Number(request.headers.get("content-length")||0)>25000)return reply(413,"Submission too large."); const host=new URL(request.url).hostname; const allowed=clean(env.ALLOWED_HOSTS||host,500).split(",").map(x=>x.trim()).filter(Boolean); if(!allowed.includes(host))return reply(403,"Unauthorized form host."); const origin=request.headers.get("origin"); if(origin&&!allowed.includes(new URL(origin).hostname))return reply(403,"Submission origin rejected."); let body;try{body=await request.json()}catch{return reply(400,"Form data could not be read.");} if(clean(body.website,100))return reply(200,"Thank you. Your request was received."); const elapsed=Date.now()-Number(body.form_started_at||0); if(!Number(body.form_started_at)||elapsed<4000||elapsed>86400000)return reply(400,"Reload the page and complete the form again."); const check=await verify(clean(body["cf-turnstile-response"],2500),env.TURNSTILE_SECRET_KEY,request.headers.get("CF-Connecting-IP")||"",host); if(!check.success)return reply(400,"Human verification failed. Please try again."); const name=clean(body["Full Name"]||body.Name||"",120); const address=clean(body.Email||body.email||"",254); const phone=clean(body.Phone||body.phone||"",50); if(name.length<2)return reply(400,"Enter a valid name."); if(!validEmail(address))return reply(400,"Enter a valid email address."); if(phone&&!/^[0-9+().\-\s]{7,25}$/.test(phone))return reply(400,"Enter a valid phone number."); const fields={}; for(const [k,raw] of Object.entries(body)){ if(["cf-turnstile-response","website","form_started_at"].includes(k))continue; fields[clean(k,100)]=clean(raw,/message|goal|description/i.test(k)?4000:500); } const combined=Object.values(fields).join("\n"); if(spam(combined))return reply(400,"This submission could not be accepted."); if(env.FORM_RATE_LIMITER){ const limited=await env.FORM_RATE_LIMITER.limit({key:`${address.toLowerCase()}:${clean(body.form_type||"form",100)}`}); if(!limited.success)return reply(429,"Too many requests. Try again later."); } if(env.FORM_DEDUP){ const raw=`${address.toLowerCase()}|${clean(body.form_type||"form",100)}|${combined}`; const hash=[...new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(raw)))].map(b=>b.toString(16).padStart(2,"0")).join(""); if(await env.FORM_DEDUP.get(hash))return reply(200,"Your request was already received."); await env.FORM_DEDUP.put(hash,"1",{expirationTtl:86400}); } try{ await email(env,`[Verified Website Lead] ${clean(body.form_type||"Website Form",100)} — ${name}`,address,fields,{host,time:new Date().toISOString()}); }catch(e){console.error(e);return reply(503,"Verification passed, but delivery is unavailable. Please call or email us.");} return reply(200,"Thank you. Your verified request was sent successfully.");
}
export function onRequestGet(){return reply(405,"Method not allowed.");}
