const looks=[
["Agency-Ready Headshot","#2c5cff","#101b48"],["Tailored Suit Editorial","#5a351f","#c7a684"],["Clean Beauty","#692b50","#e8b7ce"],["Street Style","#1f252a","#8b9298"],["Evening Editorial","#391525","#bd274d"],["Denim Commercial","#214c72","#8db9db"],["Monochrome Portrait","#111","#777"],["Movement Study","#8c351c","#f0a04b"],["Creative Beauty","#2f135c","#9c72e8"],["Lifestyle Campaign","#2f5836","#bed5a4"],["Full-Length Studio","#252525","#d6d2c9"],["Business Fashion","#273b63","#aebbd6"],["Color Story","#b51e39","#f0b325"],["Beauty Close-Up","#613b24","#e6c3a0"],["Editorial Texture","#203a32","#91b8a8"],["Natural Light","#8d7258","#e3d4c2"],["Signature Look","#111","#2c5cff"]
];
const intro=document.getElementById("intro"),logo=document.getElementById("logo3d"),label=document.getElementById("slideLabel"),progress=document.getElementById("slideProgress"),grid=document.getElementById("portfolioGrid"),site=document.getElementById("site");
setTimeout(()=>intro.classList.add("logo-ready"),140);
let i=0;function showSlide(){const x=looks[i];logo.style.setProperty("--p1",x[1]);logo.style.setProperty("--p2",x[2]);logo.style.setProperty("--p3","#f4f1ea");label.textContent="PLACEHOLDER "+String(i+1).padStart(2,"0")+" / 17";progress.style.width=((i+1)/17*100)+"%";i=(i+1)%looks.length}
showSlide();const timer=setInterval(showSlide,560);
document.getElementById("enterSite").addEventListener("click",()=>{clearInterval(timer);intro.classList.add("is-gone");site.classList.add("is-visible");site.setAttribute("aria-hidden","false");setTimeout(()=>document.querySelector(".hero").scrollIntoView(),450)});
looks.forEach((x,n)=>{const card=document.createElement("article");card.className="look-card";card.style.setProperty("--c1",x[1]);card.style.setProperty("--c2",x[2]);card.innerHTML='<span class="placeholder-tag">IMAGE PLACEHOLDER</span><div class="look-meta"><b>'+String(n+1).padStart(2,"0")+'</b><span>'+x[0].toUpperCase()+'</span></div>';grid.appendChild(card)});
const menu=document.getElementById("menuBtn"),nav=document.getElementById("nav");menu.addEventListener("click",()=>{const open=nav.classList.toggle("open");menu.setAttribute("aria-expanded",String(open))});nav.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>{nav.classList.remove("open");menu.setAttribute("aria-expanded","false")}));
if(window.matchMedia("(prefers-reduced-motion: reduce)").matches){intro.classList.add("logo-ready")}