const schools=[
['Computers','Computer Foundations A–Z','Build confidence with hardware, software, files, browsers, Wi-Fi, cloud storage, Windows, security and practical troubleshooting.'],
['AI','AI Academy','Learn AI fundamentals, ChatGPT, prompting, responsible use, productivity, automation concepts and practical business workflows.'],
['Creative','Adobe & Creator Software','Develop practical skills across Photoshop, Illustrator, Premiere Pro, After Effects, Audition, Lightroom, Acrobat, CapCut and related creator tools.'],
['Certification','Certification Prep','Study by objective with review plans, practice questions, timed drills, weak-area reinforcement and readiness tracking.'],
['Business','Business Ownership A–Z','Learn branding, pricing, sales, marketing, websites, ecommerce, operations, finance basics and practical growth systems.'],
['Creator','Creator Business School','Build stronger YouTube, digital-product, creator-website, audience, content-system and monetization foundations.']
];
const teachers=[
['byte','Professor Byte','Computer Coach','Computers & Troubleshooting','Explains computer concepts and troubleshooting steps in plain language.'],
['nova','Professor Nova','AI Guide','AI & Productivity','Helps you practice prompts, understand AI concepts and review responsible-use decisions.'],
['pixel','Designer Pixel','Creative Mentor','Creative Software','Breaks creative-software concepts into smaller steps and practical exercises.'],
['venture','Coach Venture','Business Coach','Business Ownership','Reinforces business lessons, planning frameworks and practical examples.']
];
const lessons={
computers:{tag:'COMPUTER FOUNDATIONS',title:'Why files have extensions',time:'6-minute preview',objective:'Understand what .pdf, .jpg, .docx and similar endings tell your device.',lesson:'A file extension is the group of letters after the final dot in a filename. It helps your operating system decide which app should open the file. Renaming the extension does not actually convert the file format.',tryit:'Find three files on your device. Identify each extension and the app that normally opens it.',check:'If report.pdf is renamed report.jpg, has the PDF actually become an image?',answer:'No. Renaming the extension changes the name, not the underlying file format.'},
ai:{tag:'AI ACADEMY',title:'Write a useful prompt',time:'7-minute preview',objective:'Give an AI system enough context, goal and output direction to produce a more useful first response.',lesson:'A practical prompt can state the role or context, the task, important constraints and the desired output. More words are not automatically better; relevant context is what matters.',tryit:'Rewrite “help me market my business” with the audience, goal, channel and desired format included.',check:'Which improves a prompt more: random detail or relevant constraints?',answer:'Relevant constraints. They help define what a useful answer should look like.'},
business:{tag:'BUSINESS A–Z',title:'Map one repetitive workflow',time:'8-minute preview',objective:'Spot a manual process that may be worth standardizing or automating.',lesson:'Start by mapping the trigger, steps, decisions, handoffs and final outcome. Do not automate a broken process before you understand where the friction actually occurs.',tryit:'Choose one repeated task such as responding to leads. Write its trigger, every handoff and the desired end result.',check:'What should happen before automating a workflow?',answer:'Understand and simplify the workflow first, then decide what should be automated.'}
};
const contactLinks={support:'https://www.atechspot.com/contact/?department=support&subject=A%2B%20Techucation%20Learning%20Support#contact-form',sales:'https://www.atechspot.com/contact/?department=sales&subject=A%2B%20Techucation%20Membership#contact-form',billing:'https://www.atechspot.com/contact/?department=billing&subject=A%2B%20Techucation%20Billing#contact-form'};
const enrollmentLinks={Starter:'https://www.atechspot.com/contact/?department=sales&subject=A%2B%20Techucation%20Starter%20Membership#contact-form',Pro:'https://www.atechspot.com/contact/?department=sales&subject=A%2B%20Techucation%20Pro%20Membership#contact-form',Business:'https://www.atechspot.com/contact/?department=sales&subject=A%2B%20Techucation%20Business%20Membership#contact-form'};
const testCheckout={Starter:'https://buy.stripe.com/test_9B628s9Pw7D8bdpdma6EU01',Pro:'https://buy.stripe.com/test_8x2fZi0eWg9EepBfui6EU02',Business:'https://buy.stripe.com/test_3cIdRa1j0bTo0yL5TI6EU03'};
const params=new URLSearchParams(location.search);const stripeTest=params.get('stripe-test')==='1'||location.hostname.endsWith('.workers.dev')||location.hostname.endsWith('.pages.dev');
const planUrl=plan=>stripeTest?testCheckout[plan]:enrollmentLinks[plan];
const planLabel=plan=>stripeTest?'Test Secure Checkout →':`Start ${plan} Enrollment →`;
const teacherMarkup=t=>`<article class="assistantCard teacherCard"><div class="bot ${t[0]}" aria-hidden="true"><span class="antenna"></span><span class="botHead"><i></i><i></i></span><span class="botBody">A+</span><span class="botRing"></span></div><span class="teacherRole">${t[2]}</span><h3>${t[1]}</h3><b>${t[3]}</b><p>${t[4]}</p></article>`;
const root=document.getElementById('app');
root.innerHTML=`
<a class="skip" href="#main">Skip to content</a>
<div class="topbar"><div class="wrap"><span>A+ Techucation LLC · Technology Education From A to Z</span><a href="https://www.atechspot.com/ecosystem/">Website 2 of the 22-property ATechSpot ecosystem ↗</a></div></div>
<header class="site-header"><div class="wrap navin"><a class="brand logoNoBox" href="/" aria-label="A+ Techucation home"><img src="/atechucation-logo.svg" alt="A+ Techucation — Technology Within Us"></a><button class="menuBtn" type="button" aria-controls="primaryNav" aria-expanded="false" aria-label="Open navigation">☰</button><nav class="links" id="primaryNav" aria-label="Primary navigation"><a href="#schools">Schools</a><a href="#lessons">Lessons</a><a href="#ai-support">AI Teachers</a><a href="#placement">Placement</a><a href="#membership">Membership</a><a class="btn primary" href="#placement">Start Assessment</a></nav></div></header>
<main id="main">
<section class="hero"><div class="hero-grid-pattern" aria-hidden="true"></div><div class="wrap heroGrid"><div class="heroCopy"><div class="heroLogo logoNoBox"><img src="/atechucation-logo-light.svg" alt="A+ Techucation — Technology Within Us"></div><p class="eyebrow lightEyebrow">Computers · AI · Creative Software · Certification · Business</p><h1>Learn it.<br><span>Understand it.</span><br>Use it.</h1><p class="lead">Structured technology learning for adults who want practical skills, a clear path and help when a lesson does not click.</p><div class="actions"><a class="btn primary" href="#placement">Start My Placement Assessment →</a><a class="btn glass" href="#lessons">Preview a Lesson</a></div><div class="trust"><span>6 learning schools</span><span>24/7 AI study support</span><span>Progress-based learning</span></div></div><aside class="dashboard heroDashboard"><div class="dashTop"><p class="eyebrow">Member Dashboard Preview</p><span class="livePill">DEMO</span></div><div class="dashPreviewTop"><div class="progressRing" style="--p:68"><strong>68%</strong><span>Current path</span></div><div><h2>Computer Foundations</h2><p>Next: Files, folders & cloud storage</p><span class="streak">4-day learning streak</span></div></div><div class="courseBars"><label>Computer Foundations <span>68%</span><i><b style="width:68%"></b></i></label><label>AI Academy <span>42%</span><i><b style="width:42%"></b></i></label><label>Business A–Z <span>18%</span><i><b style="width:18%"></b></i></label></div><div class="dashFoot"><span>17 lessons completed</span><span>3 active paths</span></div></aside></div></section>
<section class="proofStrip"><div class="wrap proofGrid"><div><b>6</b><span>Learning Schools</span></div><div><b>A–Z</b><span>Structured Progression</span></div><div><b>24/7</b><span>AI Study Assistance</span></div><div><b>3</b><span>Membership Paths</span></div></div></section>
<section id="schools"><div class="wrap"><div class="sectionHead"><div><p class="eyebrow">Six Learning Schools</p><h2>Know what to learn next.</h2></div><p>Each school has a practical purpose, organized progression and real-world application.</p></div><div class="grid three schoolGrid">${schools.map((c,i)=>`<article class="card schoolCard"><span class="schoolNum">0${i+1}</span><span class="tag">${c[0]}</span><h3>${c[1]}</h3><p>${c[2]}</p><a href="#placement">Find my starting level →</a></article>`).join('')}</div></div></section>
<section id="lessons" class="lessonSection"><div class="wrap"><div class="sectionHead"><div><p class="eyebrow">Actual Lesson Previews</p><h2>See how a lesson teaches before you join.</h2></div><p>These short previews demonstrate the lesson structure: objective, explanation, practice and knowledge check.</p></div><div class="lessonTabs" role="tablist" aria-label="Lesson previews"><button class="active" data-lesson="computers">Computers</button><button data-lesson="ai">AI</button><button data-lesson="business">Business</button></div><article id="lessonPanel" class="lessonPanel" aria-live="polite"></article></div></section>
<section class="darkSection" id="ai-support"><div class="wrap"><div class="sectionHead inverse"><div><p class="eyebrow lightEyebrow">Animated AI Teachers</p><h2>Four guides. Different learning jobs.</h2></div><p>These are clearly identified AI study characters—not human instructors. They supplement structured lessons with explanations, examples, quizzes and review support.</p></div><div class="grid four assistantGrid">${teachers.map(teacherMarkup).join('')}</div><div class="aiNote"><b>AI support has limits.</b><span>Verify important technical, financial, legal, certification and business decisions with authoritative sources or qualified professionals.</span></div></div></section>
<section id="placement" class="softSection"><div class="wrap placementGrid"><div><p class="eyebrow">Interactive Placement Assessment</p><h2>Start where you are—not where a generic course assumes you are.</h2><p class="sectionLead">Five quick questions run entirely in your browser. No personal information is required to get a recommendation.</p><form id="placementForm" class="placementForm"><label>1. How confident are you with everyday technology?<select name="confidence" required><option value="">Choose one</option><option value="0">I need the basics</option><option value="1">I am comfortable with common tasks</option><option value="2">I am already fairly advanced</option></select></label><label>2. What is your main goal?<select name="goal" required><option value="">Choose one</option><option value="confidence">Everyday confidence</option><option value="career">Career / professional skills</option><option value="business">Run or grow a business</option></select></label><label>3. How deep do you want to go?<select name="depth" required><option value="">Choose one</option><option value="0">Essentials first</option><option value="1">Multiple skill areas</option><option value="2">Full professional / business depth</option></select></label><label>4. What is your current AI experience?<select name="ai" required><option value="">Choose one</option><option value="0">Little or none</option><option value="1">I use AI occasionally</option><option value="2">I use AI regularly</option></select></label><label>5. How much study time can you protect each week?<select name="time" required><option value="">Choose one</option><option value="0">Under 2 hours</option><option value="1">2–5 hours</option><option value="2">5+ hours</option></select></label><button class="btn primary" type="submit">Get My Placement →</button></form></div><aside id="placementResult" class="placementResult" aria-live="polite"><span class="tag">PLACEMENT RESULT</span><h3>Your recommendation will appear here.</h3><p>Complete all five questions to see a suggested membership level and first learning path.</p></aside></div></section>
<section id="dashboard-preview"><div class="wrap"><div class="sectionHead"><div><p class="eyebrow">Member Experience Preview</p><h2>Progress should be visible.</h2></div><p>The dashboard concept makes next steps, completion and momentum easier to understand at a glance.</p></div><div class="memberMock"><aside class="memberRail"><b>A+ MEMBER</b><span class="active">Dashboard</span><span>My Paths</span><span>Practice</span><span>AI Teachers</span><span>Progress</span></aside><div class="memberMain"><div class="memberHello"><div><span class="tag">YOUR WEEK</span><h3>Keep your learning moving.</h3></div><div class="progressRing small" style="--p:74"><strong>74%</strong><span>weekly goal</span></div></div><div class="metricGrid"><div><b>17</b><span>Lessons complete</span></div><div><b>4</b><span>Day streak</span></div><div><b>86%</b><span>Practice accuracy</span></div></div><div class="nextLesson"><span>UP NEXT</span><h4>Files, folders & cloud storage</h4><p>Computer Foundations · Lesson 08 · 12 min</p><button type="button">Continue lesson →</button></div></div></div></div></section>
<section id="proof" class="proofSection"><div class="wrap proofLayout"><div><p class="eyebrow">Proof Without Fabrication</p><h2>We will not manufacture testimonials.</h2><p>Student stories and outcomes will be published only when permission and verifiable attribution are available. Until then, judge the learning experience by what you can inspect.</p></div><div class="proofCards"><a href="#lessons"><b>Lesson structure</b><span>Preview teaching before joining →</span></a><a href="#placement"><b>Placement logic</b><span>See how your starting path is selected →</span></a><a href="#dashboard-preview"><b>Progress system</b><span>Preview how learning is organized →</span></a></div></div></section>
<section class="helpChoice"><div class="wrap"><div class="sectionHead inverse"><div><p class="eyebrow lightEyebrow">Learn It or Get It Fixed</p><h2>Choose the right kind of help.</h2></div><p>A+ Techucation teaches. Other ATechSpot properties can help when you need self-help troubleshooting or hands-on support.</p></div><div class="helpGrid"><a class="helpCard" href="https://www.atechspot.com/resources/"><span>FREE PROBLEM SOLVING</span><h3>ATechSpot Tech Guru</h3><p>Use free self-help and troubleshooting resources when you want to solve a technology problem yourself.</p><b>Start with free resources →</b></a><a class="helpCard urgent" href="https://www.atechspot.com/remote-support/"><span>I NEED SOMEBODY TO FIX IT</span><h3>ATechSpot RemoteCare</h3><p>Request consent-first remote technical support when you want hands-on help diagnosing and resolving the issue.</p><b>Request RemoteCare →</b></a></div></div></section>
<section id="membership" class="softSection"><div class="wrap"><div class="sectionHead"><div><p class="eyebrow">Membership</p><h2>Choose the depth that fits your goal.</h2></div><p>${stripeTest?'Stripe test checkout is enabled for this QA session. No live charge should be created in test mode.':'Enrollment is routed securely. Live payment activation is only presented when production billing is confirmed.'}</p></div><div class="grid three pricing"><article class="card priceCard"><span class="planLevel">FOUNDATIONS</span><h3>A+ Starter</h3><div class="price">$19 <small>/ month</small></div><p>For adults building digital confidence.</p><ul><li>Computer Foundations A–Z</li><li>Beginner AI</li><li>Core digital skills</li><li>Progress tracking</li><li>Basic study support</li></ul><a class="btn blue" href="${planUrl('Starter')}">${planLabel('Starter')}</a></article><article class="card priceCard featured"><span class="badge">MOST POPULAR</span><span class="planLevel">PROFESSIONAL</span><h3>A+ Pro</h3><div class="price">$39 <small>/ month</small></div><p>For broader professional and creative development.</p><ul><li>Everything in Starter</li><li>Full AI Academy</li><li>Adobe & creator courses</li><li>Certification preparation</li><li>Practice tools</li><li>Expanded support</li></ul><a class="btn primary" href="${planUrl('Pro')}">${planLabel('Pro')}</a></article><article class="card priceCard"><span class="planLevel">OWNER / OPERATOR</span><h3>A+ Business</h3><div class="price">$79 <small>/ month</small></div><p>For owners connecting learning to execution.</p><ul><li>Everything in Pro</li><li>Business Ownership A–Z</li><li>AI for business</li><li>Automation training</li><li>Business templates</li><li>Premium support</li></ul><a class="btn blue" href="${planUrl('Business')}">${planLabel('Business')}</a></article></div><p class="fine">Recurring membership pricing is monthly. Final access, renewal, cancellation and refund terms are shown before payment when live checkout is activated. Membership does not guarantee employment, certification, income or business results.</p>${stripeTest?'<div class="testBanner"><b>Operator QA:</b> these buttons use Stripe TEST MODE payment links created for the three membership tiers.</div>':''}</div></section>
<section id="onboarding"><div class="wrap"><div class="sectionHead"><div><p class="eyebrow">Member Onboarding</p><h2>From checkout to first lesson in five steps.</h2></div><p>The onboarding path reduces uncertainty and gets a new member into the right learning track quickly.</p></div><div class="onboardingSteps"><article><b>01</b><h3>Complete secure checkout</h3><p>Confirm membership level and recurring terms.</p></article><article><b>02</b><h3>Confirm your email</h3><p>Receive membership and account instructions.</p></article><article><b>03</b><h3>Take placement</h3><p>Identify your current confidence, goals and depth.</p></article><article><b>04</b><h3>Choose the first path</h3><p>Start with one focused learning outcome.</p></article><article><b>05</b><h3>Open your dashboard</h3><p>Begin the first lesson and track progress.</p></article></div></div></section>
<section id="faq"><div class="wrap faqWrap"><div class="sectionHead"><div><p class="eyebrow">Questions</p><h2>Know what you are joining.</h2></div></div><div class="faqList"><details><summary>Are the AI teachers human instructors?</summary><p>No. Professor Byte, Professor Nova, Designer Pixel and Coach Venture are AI study characters. They support lessons but do not replace professional judgment.</p></details><details><summary>Does membership guarantee a certification or job?</summary><p>No. Learning participation does not guarantee certification, employment, income or business results.</p></details><details><summary>Can I preview the learning experience first?</summary><p>Yes. Use the lesson previews, placement assessment and member-dashboard preview on this page before choosing a membership path.</p></details><details><summary>How do I get membership or billing help?</summary><p>Use the secure support routes below. No email-compose window is required.</p></details></div></div></section>
<section class="supportSection"><div class="wrap supportGrid"><div><p class="eyebrow">Support</p><h2>Learning, membership and billing help.</h2><p>Public ATechSpot identities are used while secure forms deliver requests behind the scenes.</p></div><div class="supportCards"><a href="${contactLinks.support}"><b>Learning Support</b><span>support@atechspot.com</span></a><a href="${contactLinks.sales}"><b>Membership</b><span>sales@atechspot.com</span></a><a href="${contactLinks.billing}"><b>Billing</b><span>billing@atechspot.com</span></a></div></div></section>
<section class="ecosystemSection"><div class="wrap"><div class="sectionHead inverse"><div><p class="eyebrow lightEyebrow">Connected Ecosystem</p><h2>Education has one clear job inside a 22-property system.</h2></div><p>A+ Techucation teaches technology. ATechSpot implements technology. Every property keeps a distinct audience and conversion purpose.</p></div><div class="actions"><a class="btn light" href="https://www.atechspot.com/ecosystem/">Explore All 22 Properties →</a></div></div></section>
</main>
<div class="ecosystemNav"><div class="wrap"><a class="ecoPrev" href="https://www.atechspot.com/"><small>← Website 1</small><strong>ATechSpot</strong></a><a class="ecoHub" href="https://www.atechspot.com/ecosystem/">22-Property Ecosystem</a><a class="ecoNext" href="https://www.atechspot.com/creator/"><small>Website 3 →</small><strong>ATechSpot Creator</strong></a></div></div>
<footer class="footer"><div class="wrap footerGrid"><div><a class="logoNoBox" href="/"><img class="footerLogo" src="/atechucation-logo-light.svg" alt="A+ Techucation"></a><p>Technology education from A to Z. A specialized education property operated by A+ Techucation LLC.</p></div><div><h3>Learn</h3><a href="#schools">Schools</a><a href="#lessons">Lesson Previews</a><a href="#placement">Placement</a><a href="#membership">Membership</a></div><div><h3>Help</h3><a href="https://www.atechspot.com/resources/">Tech Guru Resources</a><a href="https://www.atechspot.com/remote-support/">RemoteCare</a><a href="${contactLinks.support}">Learning Support</a><a href="${contactLinks.billing}">Billing</a></div><div><h3>Policies</h3><a href="/privacy/">Privacy</a><a href="/terms/">Terms</a><a href="/accessibility/">Accessibility</a><a href="https://www.atechspot.com/ecosystem/">All 22 Properties</a></div></div><div class="wrap legal">© 2026 A+ Techucation LLC. Educational participation does not guarantee employment, certification, income or business results.</div></footer>`;

function renderLesson(key){const l=lessons[key];document.querySelectorAll('[data-lesson]').forEach(b=>b.classList.toggle('active',b.dataset.lesson===key));document.getElementById('lessonPanel').innerHTML=`<div class="lessonMeta"><span>${l.tag}</span><span>${l.time}</span></div><h3>${l.title}</h3><div class="lessonCols"><div><b>OBJECTIVE</b><p>${l.objective}</p><b>MINI LESSON</b><p>${l.lesson}</p></div><div class="tryBox"><b>TRY IT</b><p>${l.tryit}</p><details><summary>Knowledge check</summary><p>${l.check}</p><strong>${l.answer}</strong></details></div></div>`}
renderLesson('computers');document.querySelectorAll('[data-lesson]').forEach(b=>b.addEventListener('click',()=>renderLesson(b.dataset.lesson)));
const form=document.getElementById('placementForm');form.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(form);const confidence=Number(d.get('confidence')),depth=Number(d.get('depth')),ai=Number(d.get('ai')),time=Number(d.get('time')),goal=d.get('goal');let score=confidence+depth+ai+time;let plan='Starter';if(goal==='business'||score>=6)plan='Business';else if(goal==='career'||score>=3)plan='Pro';const first=goal==='business'?'Business Ownership A–Z + AI for Business':goal==='career'?'AI Academy + Certification/Creative track':'Computer Foundations A–Z + Beginner AI';const why=plan==='Starter'?'A focused foundations path keeps the learning load manageable while you build confidence.':plan==='Pro'?'Your answers point to broader professional depth across multiple skill areas.':'Your answers point to deeper owner/operator learning that connects AI, automation and business systems.';document.getElementById('placementResult').innerHTML=`<span class="tag">YOUR PLACEMENT</span><h3>A+ ${plan}</h3><p>${why}</p><div class="resultPath"><b>Suggested first path</b><span>${first}</span></div><a class="btn primary" href="${planUrl(plan)}">${stripeTest?'Test Secure Checkout':'Start '+plan+' Enrollment'} →</a><small>This is a learning-path recommendation, not an academic or employment assessment.</small>`;});
const menu=document.querySelector('.menuBtn'),nav=document.getElementById('primaryNav');menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close navigation':'Open navigation')});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}));